---
#   become: true
#   connection: ssh

#   tasks:
  #- name: "Install VIM"
  #  apt: pkg=vim state=installed

  # Need to figure out how to get IP address info
  #- name: "Configure static IP Addresses"

# - name: Create the hosts file for all machines
#   apt: update_cache=yes cach_valid_time=3600

- include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution }}.yml"
    - "../vars/default.yml"

- name: "Change hostname"
  hostname:
    name: "{{ inventory_hostname }}"

- name: "Update /etc/hosts"
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item}}$'
    line: "{{ hostvars[item].ansible_ssh_host }} {{ hostvars[item].ansible_host }} {{ item }}"
    state: present
  when: hostvars[item].ansible_host is defined
  with_items: "{{ groups.all }}"

- name: "Set root password"
  user:
    name: root
    update_password: always
    password: "{{ root_password | password_hash('sha512') }}"

- name: "Enable root login"
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: PermitRootLogin prohibit\-password
    line: PermitRootLogin yes
    state: present
  
- name: "Reload ssh"
  systemd: 
    name: "{{ ssh_svc_name }}"
    state: reloaded

- name: "Add master public key to other"
  authorized_key:
    user: root
    key: "{{ hostvars[item].master_public_key.stdout }}"
  with_items:  "{{ groups.boot }}" 

- name: "Update NTP (Network Time Protocol) settings"
  package:
    name: ntp
  
# # # # Need to update the /etc/ntp.conf file with ntp info.  geerlingguy.ntp ?

- name: "Configure sysctl"
  sysctl:
    name: vm.max_map_count
    state: present
    sysctl_set: yes
    value: '262144'
  
- name: "Install NFS client packages"
  package:
    name: "{{nfs_client_package_name}}"
    state: present

- name: "Install git-core"
  package:
    name: git-core
    state: present
  when: ansible_distribution == 'SLES'