---
#
# NOTES:
#
# Root privilege is needed to run this configuration script.
# The tasks where root is needed use the "become" option.
#
# Sample invocation (all on one line):
#   ansible-playbook -i hosts site.yml --extra-vars "ansible_become_pass=<password> root_password=<root_password>"

- name: Apply boot config
  hosts: boot
  become: yes
  roles:
    - boot

- name: Apply base icp config to all nodes
  hosts: all
  become: yes
  roles:
    - base
